### ISSUE TITLE
can you do some below update?

### ISSUE THREAD

**Issue by suriyaJaay** [zackproser/tweet-map#1]
hi,

is that possible to do below queries ?
1.  user defined keyword search
2. manual storing real time data into mongoDB with user defined keyword
3 auto store for every 30 mins into mongodb with user defined keyword

Thank you

**Comment by zackproser** [comment]
Hi, 

Yes, it would be possible to modify this project to meet the requirements you have outlined. Feel free to fork the project and modify your fork to your heart's content.
